### PR TITLE
Spaincoin support

### PR DESCRIPTION
**Pull request by youvnor**
Added spain coin support
Change Readme accordingly
Added my own p2pool nodes tu bootstrap nodes

### CODE REVIEW

**Comment by donSchoe** [comment]
This one misses the spaincoin object in p2pool/bitcoin/networks.py - doesnt it?

**Comment by youvnor** [comment]
It has it in p2pool/networks.py.
Look at it.

**Comment by donSchoe** [comment]
Look at this please.
https://github.com/youvnor/p2pool-n/blob/master/p2pool/bitcoin/networks.py

**Comment by youvnor** [comment]
the is no spain coin there.
The one i pulled is this:
https://github.com/youvnor/p2pool-n/blob/master/p2pool/networks.py

your path as a /bitcoin more and is not shown on changed files.
i did not think i committed that file.
i have to change it too ?

Sorry if i made something wrong i'm really new on github

**Comment by youvnor** [comment]
added the missing file

**Pull request merged**
