### PR TITLE
change p2p port for 2nd vertcoin network

### PR DESCRIPTION
**Pull request by DragonShow**
change p2p port to be able to run both network on the same server

solve this:

> Error binding to P2P port: Couldn't listen on any:9346: [Errno 98] Address already in use.

### CODE REVIEW

**Comment by donSchoe** [comment]
TBH I dont get this. You have both p2p ports available in your vertcoind or are you running two instances of the daemon to have both available?

Doesn't that affect people who only wish to run one of the both networks? In that case I'm not going to change that in this repository.

**Comment by DragonShow** [comment]
I'm running only one instance of vertcoind
The p2p port vertcoind is listening to is in master/p2pool/bitcoin/networks.py and is 5889, both p2pool process are able to connect to this port

The p2p port i want to change is the one the 2nd network p2pool process is listening to for other p2pool node to connect
I first thought that yes that may affect people that already have their p2pool running as they need to switch port but that seems to work fine, i am currenlty using the port 9345 for the first network and others nodes are still able to connect to mine: http://37.187.245.219:9171/static/

**Comment by donSchoe** [comment]
I'm gonna merge this as this only affects the 2nd network. If it forks or breaks we can revert it without breaking the main network.

**Comment by DragonShow** [comment]
All nodes don't need to be updated in sync as they already have a node list with their p2p ports into data/vertcoin2/addrs, upon switching, nodes will still connect to the nodes in this list and spread their new port so that others nodes add those nodes to their own list
Already running nodes don't need to update if they don't need it

The only problem is for new nodes who don't have a node list into data/vertcoin2/addrs, they use the BOOTSTRAP_ADDRS field and use by default the port they are using, so it is needed to specify to check both port

**Comment by donSchoe** [comment]
Should be no problem at all as nodes not only share their IP but also the port.

**Pull request merged**
